### ISSUE TITLE
convert: Not a JPEG file: starts with 0x0a 0x0a

### ISSUE THREAD

**Issue by ganjiste** [IbrahimButt/Direwolf-Arch-Rice#5]
When I use the "jpeg" file with the the wal command I get an error that tells me that its not a jpeg but png file. Im curious on how it works for other. Maybe something changed on the way the image is being saved ?

> [user@Arch ~]$ wal -i Pictures/Wal/bg1.jpg 
[I] image: Using image bg1.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
convert: Not a JPEG file: starts with 0x0a 0x0a `/home/user/Pictures/Wal/bg1.jpg' @ error/jpeg.c/JPEGErrorHandler/332.
convert: no images defined `txt:-' @ error/convert.c/ConvertImageCommand/3288.
Traceback (most recent call last):
  File "/bin/wal", line 11, in <module>
    load_entry_point('pywal==3.1.0', 'console_scripts', 'wal')()
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 198, in main
    parse_args(parser)
  File "/usr/lib/python3.7/site-packages/pywal/__main__.py", line 154, in parse_args
    sat=args.saturate)
  File "/usr/lib/python3.7/site-packages/pywal/colors.py", line 149, in get
    colors = getattr(backend, "get")(img, light)
  File "/usr/lib/python3.7/site-packages/pywal/backends/wal.py", line 77, in get
    colors = gen_colors(img)
  File "/usr/lib/python3.7/site-packages/pywal/backends/wal.py", line 38, in gen_colors
    raw_colors = imagemagick(20, img, has_im())
  File "/usr/lib/python3.7/site-packages/pywal/backends/wal.py", line 19, in imagemagick
    return subprocess.check_output([*magick_command, img, *flags]).splitlines()
  File "/usr/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['magick', 'convert', '/home/user/Pictures/Wal/bg1.jpg[0]', '-resize', '25%', '-colors', '20', '-unique-colors', 'txt:-']' returned non-zero exit status 1.

**Comment by ibrahimbutt** [comment]
Hey @ganjiste, I downloaded the image and it's definitely still a JPEG, so nothing has changed regarding how it's saved.

I have a MacBook Pro now and it's not compatible with Linux, so I can't test this out. Your best bet would be to make an issue on the [Pywal repo](https://github.com/dylanaraps/pywal).
